<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Token.fs" />
    <Compile Include="AST.fs" />
    <Compile Include="Lexer.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="GenC.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Megu.ParserComb\Megu.ParserComb.fsproj" />
  </ItemGroup>

</Project>
